AllCops:
  NewCops: enable
Layout/FirstArgumentIndentation:
  EnforcedStyle: special_for_inner_method_call_in_parentheses
Layout/FirstHashElementIndentation:
  EnforcedStyle: special_inside_parentheses
Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/LineLength:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/EmptyBlock:
  Enabled : false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/RescueException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodParameterName:
  AllowNamesEndingInNumbers: true
  MinNameLength: 1
Naming/PredicatePrefix:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MinMaxComparison:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/RescueStandardError:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  ConsistentQuotesInMultiline: true
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Style/YodaCondition:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false

# Project-specific configurations

# Disable filename convention for gem files
# These files are named after their corresponding gems (e.g., rack-attack, rails-i18n)
Naming/FileName:
  Exclude:
    - 'gem/**/*'

# Allow eval in internal template utilities
# This is used to load internal configuration files with controlled paths
Security/Eval:
  Exclude:
    - 'lib/base.rb'
