name: "api-docs"

services:
  nginx:
    build: .
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - nginx-log:/var/log/nginx
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token-file /run/secrets/cf_tunnel_token
    secrets:
      - cf_tunnel_token

secrets:
  cf_tunnel_token:
    file: ./.secrets/cf_tunnel_token

volumes:
  nginx-log:
