name: "rails-app-test"

x-common: &common
  env_file:
    - .env.example
    - .env

x-pg-common: &pg-common
  image: postgres:18-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
  expose:
    - 5432

x-rails-common: &rails-common
  image: local/rails-app:test
  build:
    context: .
    args:
      RAILS_ENV: test
      BUNDLE_DEPLOYMENT: false
      BUNDLE_WITHOUT: ""
      APP_UID: ${APP_UID:-1000}
      APP_GID: ${APP_GID:-1000}
  depends_on:
    pg:
      condition: service_healthy

services:
  pg:
    <<: [*common, *pg-common]
    environment:
      POSTGRES_PASSWORD_FILE: ${APP_POSTGRES_PASSWORD_FILE}
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_DB: ${APP_POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    secrets:
      - pg_password
  rails:
    <<: [*common, *rails-common]
    environment:
      APP_RAILS_MAX_THREADS: 5
      APP_RAILS_MIN_THREADS: 5
      APP_WEB_CONCURRENCY: 0
    volumes:
      - .:/rails
      - rails_logs:/rails/log
      - rails_tmp:/rails/tmp
    secrets:
      - pg_password
      - rails_secret_key_base

volumes:
  pg_data:
  rails_logs:
  rails_tmp:

secrets:
  pg_password:
    file: ./.secrets/pg_password
  rails_secret_key_base:
    file: ./.secrets/rails_secret_key_base
