name: "rails-app-test"

x-pg-common: &pg-common
  image: postgres:18-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
  expose:
    - 5432

# Shared rails service configuration
x-rails-common: &rails-common
  build:
    context: .
    args:
      # Set custom GitLab host if using self-hosted GitLab
      GITLAB_HOST: ${GITLAB_HOST:-gitlab.com}
      # Git commit SHA for Sentry release tracking
      REVISION: ${REVISION:-}
      # Test build configuration
      RAILS_ENV: test
      BUNDLE_DEPLOYMENT: false
      BUNDLE_WITHOUT: ""
      USER_ID: ${UID:-1000}
      GROUP_ID: ${GID:-1000}
  env_file:
    - .env
  depends_on:
    pg:
      condition: service_healthy
  environment:
    APP_RAILS_MAX_THREADS: 5
    APP_RAILS_MIN_THREADS: 5
    APP_WEB_CONCURRENCY: 0

services:
  # PostgreSQL Database
  pg:
    <<: *pg-common
    environment:
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: ${APP_POSTGRES_PASSWORD_FILE}
      POSTGRES_DB: ${APP_POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    secrets:
      - database_password

  # Rails Test Service
  rails:
    <<: *rails-common
    volumes:
      - .:/rails
      - rails-logs:/rails/log
      - rails-tmp:/rails/tmp
    secrets:
      - database_password
      - rails_secret_key_base

secrets:
  database_password:
    file: ./.secrets/database_password
  rails_secret_key_base:
    file: ./.secrets/rails_secret_key_base

volumes:
  pg-data:
  rails-logs:
  rails-tmp:
