name: "rails-app-dev"

x-common: &common
  restart: unless-stopped
  env_file:
    - .env.example
    - .env
  networks:
    - rails_app_dev

x-pg-common: &pg-common
  image: postgres:18-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s
  expose:
    - 5432

x-redis-common: &redis-common
  image: valkey/valkey:8-alpine
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s
  expose:
    - 6379

x-rails-common: &rails-common
  image: local/rails-app:dev
  build:
    context: .
    args:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: false
      BUNDLE_WITHOUT: ""
      APP_UID: ${APP_UID:-1000}
      APP_GID: ${APP_GID:-1000}
  depends_on:
    pg:
      condition: service_healthy
    redis_cache:
      condition: service_healthy
    redis_cable:
      condition: service_healthy
    redis_session:
      condition: service_healthy

services:
  pg:
    <<: [*common, *pg-common]
    environment:
      POSTGRES_PASSWORD_FILE: ${APP_POSTGRES_PASSWORD_FILE}
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_DB: ${APP_POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    secrets:
      - pg_password
  redis_cache:
    <<: [*common, *redis-common]
    volumes:
      - redis_cache_data:/data
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_CACHE_PASSWORD_FILE)" \
          --maxmemory 1gb \
          --maxmemory-policy allkeys-lru \
          --save ""
    secrets:
      - redis_cache_password
  redis_cable:
    <<: [*common, *redis-common]
    volumes:
      - redis_cable_data:/data
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_CABLE_PASSWORD_FILE)" \
          --maxmemory 512mb \
          --maxmemory-policy noeviction \
          --save ""
    secrets:
      - redis_cable_password
  redis_session:
    <<: [*common, *redis-common]
    volumes:
      - redis_session_data:/data
    command:
      - sh
      - -c
      - |
        redis-server \
          --requirepass "$$(cat $$APP_REDIS_SESSION_PASSWORD_FILE)" \
          --maxmemory 512mb \
          --maxmemory-policy noeviction \
          --appendonly yes \
          --appendfsync everysec
    secrets:
      - redis_session_password
  rails:
    <<: [*common, *rails-common]
    healthcheck:
      test: ['CMD', "curl", "-fsS", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    stop_signal: SIGTERM
    stop_grace_period: 10s
    environment:
      APP_RAILS_MAX_THREADS: 5
      APP_RAILS_MIN_THREADS: 5
      APP_WEB_CONCURRENCY: 0
      APP_SESSION_COOKIE_SAME_SITE: none
    expose:
      - 3000
    volumes:
      - .:/rails
      - rails_logs:/rails/log
      - rails_tmp:/rails/tmp
    secrets:
      - pg_password
      - redis_cache_password
      - redis_cable_password
      - redis_session_password
      - rails_secret_key_base
      - mailer_smtp_password
  cloudflared:
    image: cloudflare/cloudflared:latest
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:2000", "ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: tunnel --metrics 0.0.0.0:2000 run --token-file /run/secrets/cf_tunnel_token
    secrets:
      - cf_tunnel_token
    networks:
      - rails_app_dev

volumes:
  pg_data:
  redis_cache_data:
  redis_cable_data:
  redis_session_data:
  rails_logs:
  rails_tmp:

secrets:
  pg_password:
    file: ./.secrets/pg_password
  redis_cache_password:
    file: ./.secrets/redis_cache_password
  redis_cable_password:
    file: ./.secrets/redis_cable_password
  redis_session_password:
    file: ./.secrets/redis_session_password
  rails_secret_key_base:
    file: ./.secrets/rails_secret_key_base
  mailer_smtp_password:
    file: ./.secrets/mailer_smtp_password
  cf_tunnel_token:
    file: ./.secrets/cf_tunnel_token

networks:
  rails_app_dev:
    external: true
